### ISSUE TITLE
[채팅] 채팅 목록 기능 개발

### ISSUE THREAD

**Issue by Lee-JeongEun23** [djyoon956/OWL#19]
### 개요 
 - Header의 채팅 아이콘 클릭 시 오른쪽 사이드에서 나타나는 채팅 메뉴이다.

### Task
-  [ ] 채팅은 같은 프로젝트에 참여해 있는 사람하고만 가능  
 - [ ] 채팅 방 검색 시 autocomplete 실행 (검색조건은 채팅참여자, 채팅방이름 like 카카오톡)
 - [ ] 채팅 방 추가 시 단체 채팅 또는 1:1 채팅 설정에 따라 채팅 방 설정이 달라짐
      ex) 단체 채팅 방- 채팅 방 이름 설정, 채팅 방 프로필 설정, 참여 인원 초대 항목이 나타남
          1:1 채팅 방 - 채팅 방 이름 설정, 채팅 방 프로필 설정 disabled, 참여 인원 초대 항목만 설정 가능 
 - [ ] 채팅 방 참여 인원 초대 시 autocomplete 실행 (상대방의 프로필, 이름, 이메일 동시에 보여주기)
 - [ ] 채팅 방 설정 중 삭제를 원하는 채팅방을 선택하여 삭제하면 해당 채팅방 채팅 목록에서 삭제
 - [ ] 편집 된 채팅 방은 DB에서 delete
 - [ ] 채팅 방 설정 중 최신 순 정렬 시 시간에 따른 최신 메시지부터 내림차순으로 정렬
 - [ ] 채팅 방 설정 중 안 읽은 순 정렬 시 가장 새로운 메시지 알림이 많은 채팅방부터 내림차순으로 정렬
 - [ ] 새로운 메시지 확인 시 새로운 메시지 알림 제거
 - [ ] 특정 채팅방을 채팅 목록 상단에 고정 시 채팅 목록 스크롤을 내려도 상단에 위치 고정 
 - [ ] 프로젝트에 참여 시 자동적으로 해당 프로젝트 채팅 방 생성

 ---
- 채팅 방 → 채팅 목록
- [ ] 단체 채팅 방 생성자가 채팅 방 내에서 채팅 방 프로필과 이름을 수정 시 참여자의 목록에서 수정된 프로필과 이름으로 실시간 변경
