### ISSUE TITLE
[드라이브] VIEW 구현

### ISSUE THREAD

**Issue by djyoon956** [djyoon956/OWL#23]
### 개요
- project 내의 드라이브 기능

### Task
- View 잔디 참고
- [x] 좌측에 폴더 구조로 보여준다.
- [x] 최초 생성시 프로젝트 명으로 Default 폴더 생성된다.
- [x] 폴더 구조 하단에 휴지통 아이콘 클릭시 휴지통 화면으로 전환된다.
    - 휴지통에는 파일만 올 수 있다.
- [x] 폴더 삭제시 안에 파일이 있으면 alert 창으로 확인 받고, 파일은 휴지통으로 옮긴다.
- [x] 파일 삭제시 alert 창으로 확인 받고, 파일은 휴지통으로 옮긴다.
- [x] 좌측에 폴더 선택시,  폴더에 포함된 폴더, 파일을 보여준다
   - 아이콘 형식, 테이블 형식으로 보여주기 가능
- [x] 업로드 버튼으로 업로드, 화면에 파일 드랍시 업로드 가능
- [x] 검색  아이콘 클릭시 검색 창 표현 (메뉴 상단)
   - 파일 확장자, 올린 사람, keyword로 검색 가능하다.

#### JSTree 자료 조사
