### ISSUE TITLE
[채팅] 채팅방 VIEW 구현

### ISSUE THREAD

**Issue by Lee-JeongEun23** [djyoon956/OWL#29]
### 개요 
 - 오른쪽 사이드에서 나타나는 채팅 메뉴 클릭 시 나타나는 채팅 방이다.

### Task
 - [ ] 채팅 방 상단에 뒤로 가기 버튼, 단체 채팅 : 채팅 방 이름 / 1:1 채팅 : 상대방 이름, 검색, 채팅방 내부 메뉴 버튼 고정
 - [ ] 검색 시 autocomplete 적용
 - [ ] 본인이 보낸 메시지는 오른쪽에 위치하며 메시지 내용과 보낸 시간만 출력
 - [ ] 상대방이 보낸 메시지는 왼쪽에 위치하며 상대방의 프로필, 이름, 메시지 내용, 보낸 시간 출력
 - [ ] 채팅 메시지의 오른쪽 버튼 클릭 시 Select 박스 출력(북마크 / 공지사항 등록)
 - [ ] 현재까지의 채팅 방 내용 모두 출력
 - [ ] 하루 단위로 채팅 내용 구분 ex) 2020년 1월 1일 
 - [ ] 채팅 메시지 입력 창 맨 앞에 + 버튼 설정
 - [ ] 채팅 메시지 입력 창 맨 뒤에 이모티콘 버튼 및 전송 버튼 설정
 - [ ] + 버튼 - 파일 및 사진 전송, color script 적용 
 - [ ] 채팅 방 내부 메뉴 버튼 - 채팅방 서랍 > 사진, 동영상, 파일, 링크 / 공지사항 / 북마크 / 대화상대 > 대화상대 초대, 참여인원 정보(프로필, 이름) / 하단 > 채팅방 나가기, 채팅방 고정
   - 만약 대화상대 초대 버튼을 클릭 하면 채팅 목록에서의 채팅 방 만들기와 같은 Modal창 출력(단, 기존 회원은 이미 참여인원에 들어가 있음)
 - [ ]  단체 채팅방 생성자는 채팅 방 내부 메뉴 하단에 채팅방 설정 아이콘 생성 (Team, project 단체 채팅방에서는 Team Leader 또는 PM에게만 생성)
 - [ ] 채팅방 설정 아이콘 클릭 시 채팅방 프로필, 채팅방 이름 수정 가능
