### ISSUE TITLE
[회원 메인] VIEW 구현_SideBar

### ISSUE THREAD

**Issue by Lee-JeongEun23** [djyoon956/OWL#42]
### 개요
 - 로그인 성공한 하면 이동 할 메인 페이지

### Task
 - [x] Side Bar 구현
   - My Task
     - 확장 형태 고정 
     - 화면 : 대시보드, 캘린더
  - [x] Favorite 
     - 프로젝트 클릭시, 해당 프로젝의 Team으로 변경되고 project 메인 출력
     - mouse over 시, 해당 프로젝트 색상으로 표현된다.
 - [x] Project 
     -  ~~Team 변경에 따라 list up~~
     -  확장 형태 고정
      - mouse over 시, [favorite 이모티콘] 팀 명 [설정 이모티콘]

### 기능

- side bar에서 new project 생성 모달
- [x] PM인 사용자에게만 new project 메뉴가 보임
- [ ]  프로젝트 명 중복 검사(비동)
- [ ]  정상 입력시 db insert (프로젝트 타이틀, 기간, 색)
- [ ]  설정 클릭 시 색 수정 가능 및 즐겨찾기 추가
