### ISSUE TITLE
[회원가입] VIEW 구현

### ISSUE THREAD

**Issue by djyoon956** [djyoon956/OWL#7]
### 개요
- 메인 페이지의 상단 우측에 위치한 로그인/회원가입을 누르면 모달 창으로 접근 가능하다.

### Task
- [x]  회원가입 모달 창
- [x]  입력 조건 (프로필 사진, 이메일 (인증), 비밀번호, 이름 )
- [x]  회원 가입 이메일 링크 폼 구현(velocity)
- [x]  이메일 인증 확인 화면 구현
- [x]  링크 타고 들어온 화면 구현
